### PR TITLE
[WIP] New'Sie port/GC port

### PR DESCRIPTION
**Pull request by scrdest**
I should have isolated all-ish commits that are related only to these two and skipped the rest, although because TortoiseGit is a dumb, it needs some more work before it compiles properly.

Putting this in here in case someone is able to help me out in fixing mostly the dumb formatting issues brought on by Git.

### CODE REVIEW

**Comment by Glloyd** [comment]
>scrdest wants to merge 1,464 commits

uhhhh

**Comment by scrdest** [comment]
It looks like that because git iz dum. I've managed to get rid of all the extraneous code which got thrown in there somehow.

**Comment by Glloyd** [comment]
The issue with that is that it's going to mess things up down the line when I merge master. Git's going to think all those commits are already there. We'd be better off merging dev freeze when that happens, but I want to finish my master merge first so we have less to hash through.

**Comment by scrdest** [comment]
Hokay. I doubt git is *that* dumb, although I'm more than willing to retract that statement very, very quickly.

I wish there was an option to merge the diff of a commit relative to codebase >_>

**Comment by Glloyd** [comment]
you can always cherry pick specific commits.

**Comment by scrdest** [comment]
Get on Steam, okay?

**Comment by scrdest** [comment]
Blergh, it is probably quite pointless to bother. The port came juuuuuuust after a completely unrelated antag refactor and likewise completely unrelated mob refactor, and this PR touches on both of these. Too many dependencies out of scope.

**Comment by TGameCo** [comment]
What is New'Sie? A version of Nar'sie that isn't just a re-textured singularity?

**Comment by scrdest** [comment]
Kinda, yeah. It's based of off a thing /vg/ did, ported to BS12 already - you can make Nar'Sie act like he does now, or, by new default, to cultify the station, turning Cultists into Harvesters, items into their cult equivalents (like cultwalls, but also, ferex, swords into cult blades), opening portals spawning assorted hellbeasts who will charge the escape shuttle if non-cult crew tries to escape.

Or, alternatively, summoning may literally break reality, forcing the survivors - of the human race, not just the station, as EVERYTHING else turns into Supermatter - to flee into another universe through a portal.

**Pull request closed without merging**
