### PR TITLE
Map changes to R&D and Toxins

### PR DESCRIPTION
**Pull request by liction15**
Map changes to R&D and Toxins. 
See: http://i.imgur.com/zCu48b0.png
and http://i.imgur.com/b0GPaCo.png

R&D is functionally the same with only
minor changes to the placement of the equipment and tables to make it
easier to not get yourself stuck and generally seems more open.

Toxins Lab has been significantly altered, especially the canister room,
but not so much that it also changes the surrounding area by much. Major
changes include, the addition of 6 gas coolers for cooling whatever gas
you want to cool, a reworked burn chamber (inspired by the one on hippie
station) where it uses heat transfer pipes to heat gasses rather then
burning the gasses directly so that you can heat a variety of gasses if
you wished to do so and a addition of a small area that connects to the
exit, canister room and toxins lab. This is a complete change in the
layout and design of the Toxins Lab without significantly altering the
areas around it or its location.

I hope these changes will help in general and also make it easier for
toxins techs (or antags) to do their jobs and experiment with the new
changes.

### CODE REVIEW

**Comment by liction15** [comment]
It also took me 2 hours to even figure out how to even make a pull request.

Something else i should mention is that it would be good for someone to give the pipes, buttons and burn chamber airlock a check to make sure they work and also to fix any changes from the baymerge of doom.

**Comment by Glloyd** [comment]
I love it. I'll merge it into the Bay merge once the map gets unfucked.

On Wed, Sep 16, 2015 at 11:19 PM, liction15 <notifications@github.com>
wrote:

> It also took me 2 hours to even figure out how to even make a pull request.
>
> Something else i should mention is that it would be good for someone to
> give the pipes, buttons and burn chamber airlock a check to make sure they
> work and also to fix any changes from the baymerge of doom.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/pull/285#issuecomment-140898164>
> .
>



-- 
Graham Lloyd

**Comment by liction15** [comment]
I just noticed a minor problem but the canister room is missing an air alarm. Im not really sure how to change things on github but it should be simple to fix that when you fix the map.

**Comment by Flip-Sandwich** [comment]
R&D changes are Good. Very Good.

Honestly not a fan of toxins changes, with the ~mad science~ and ~shenanigans~ I get up to it feels like it'd just be... easymode. And that single vent with that single space tile right in the middle of everything combined with ZAS also looks like easymode for ruining R&D for the round.

**Comment by liction15** [comment]
making Toxins easymodo is kinda the point and the rest of R&D is behind several layers of r-walls, windows and doors so I don't think it would adversely affect things considering toxins tends to either get flooded or exploded when someone messes up normally. 

I have however heard other people talk about the placement of the space tile there and I will concede that might not be the best place for it and I will reconsider the placement of that or even nix that bit entirely but for now this isn't getting added until the map and code un-fubaring gets done.

**Comment by Flip-Sandwich** [comment]
but why would you make mass murder and bombing easymodo, surely the idea is that you'd have to you know spend some time and effort on it

**Comment by liction15** [comment]
Because I feel like giving traitors more options to do things with bombs can be a good thing. Hell even if this change gets in there is no guarantee traitors will even use bombs more often. This is all assuming traitors don't go murderbonering the entire station, for that we have admins to enforce the rules. If after this gets merged people don't like it we can either revert the changes to toxins or scale it back to not include the coolers.

**Comment by liction15** [comment]
seeing as how things probably have changed map wise it might be better to close this for now. I might come back to this depending if I ever finish mapping an entirely new station.

**Comment by Glloyd** [comment]
alright. you can edit the map now on my branch btw. it all works fine.

**Pull request closed without merging**
