### PR TITLE
Bay Merge Part Two: Electric Fuckaloo

### PR DESCRIPTION
**Pull request by Glloyd**
# Ow.

- [x] Merge Bay back in May
- [ ] rand handcuff time
- [x] add urist underwear back in

# PART TWO

- [x] Merge current Bay master
- [x] Figure out wtf I gotta do
- [x] revert what needs to be reverted
- [x] revert the fuck out of those chem changes
- [x] fix the map
- [x] make it compile
- [x] complete the todo lists below
- [x] test and fix the guns
- [x] test the couches
- [x] fix the engine
- [x] fix the asteroid
- [ ] fix the easels
- [ ] fix emplacements
- [x] fix bedsheet and hazardvest bandana icons
- [x] put lights on the shuttles
- [x] check for anything i forgot to add to the map
- [ ] port over the stuff from my other branch (leave this to the end)
- [x] call it a day, update main server, prepare for hotfixing

### CODE REVIEW

**Comment by Glloyd** [comment]
@scrdest

**Comment by Skeeve2** [comment]
Mother of god.

**Comment by Glloyd** [comment]
By the time I finish part two and merge in some of my other local branches, this PR will be near (if not over) 3000 commits.

**Comment by scrdest** [comment]
'Undo hitscan bullets'?
You mean the PTRS? Because it has a very good reason for being made that way. Unless I missed some other change.

Chem changes - you mean the container... things, right?

**Comment by Glloyd** [comment]
No, I mean bay made all bullets hitscan, not just lasers as they were
before.

On Mon, Aug 17, 2015 at 4:36 AM, scrdest <notifications@github.com> wrote:

> 'Undo hitscan bullets'?
> You mean the PTRS? Because it has a very good reason for being made that
> way. Unless I missed some other change.
>
> Chem changes - you mean the container... things, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/pull/277#issuecomment-131730547>
> .
>



-- 
Graham Lloyd

**Comment by Glloyd** [comment]
Also, yeah, that nonsense.

On Mon, Aug 17, 2015 at 5:12 PM, Graham Lloyd <glloyd9714@gmail.com> wrote:

> No, I mean bay made all bullets hitscan, not just lasers as they were
> before.
>
> On Mon, Aug 17, 2015 at 4:36 AM, scrdest <notifications@github.com> wrote:
>
>> 'Undo hitscan bullets'?
>> You mean the PTRS? Because it has a very good reason for being made that
>> way. Unless I missed some other change.
>>
>> Chem changes - you mean the container... things, right?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/UristMcStation/UristMcStation/pull/277#issuecomment-131730547>
>> .
>>
>
>
>
> --
> Graham Lloyd
>



-- 
Graham Lloyd

**Comment by Glloyd** [comment]
I may go about this in a different way. I'm going to try something tomorrow, and if it doesn't work then we'll go back to this and drag this out through the week.

**Comment by scrdest** [comment]
What? I am almost 99% sure they very specifically did NOT make all bullets hitscan, and the code apparently agrees - only the PTR is a hitscan projectile weapon, and that's to make it worthwhile as a high-powered sniper rifle.

**Comment by Zuhayr** [comment]
>No, I mean bay made all bullets hitscan, not just lasers as they were before

Based on what, exactly?

**Comment by Glloyd** [comment]
I thought that was part of the gun overhaul? I wrote it down on my list at
least. Seems like I made a mistake, whoops.

On Tue, Aug 18, 2015 at 9:50 AM, Zuhayr <notifications@github.com> wrote:

> No, I mean bay made all bullets hitscan, not just lasers as they were
> before
>
> Based on what, exactly?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/pull/277#issuecomment-132214674>
> .
>



-- 
Graham Lloyd

**Comment by Glloyd** [comment]
Ahhh, I figured it out. It was from Loganbacca's projectile effects PR.
They originally included making bullets hitscan as part of the PR and I
must've forgot to take it off my list.

On Tue, Aug 18, 2015 at 5:06 PM, Graham Lloyd <glloyd9714@gmail.com> wrote:

> I thought that was part of the gun overhaul? I wrote it down on my list at
> least. Seems like I made a mistake, whoops.
>
> On Tue, Aug 18, 2015 at 9:50 AM, Zuhayr <notifications@github.com> wrote:
>
>> No, I mean bay made all bullets hitscan, not just lasers as they were
>> before
>>
>> Based on what, exactly?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/UristMcStation/UristMcStation/pull/277#issuecomment-132214674>
>> .
>>
>
>
>
> --
> Graham Lloyd
>



-- 
Graham Lloyd

**Comment by Glloyd** [comment]
Poll is up on the server about what to do in regards to https://github.com/Baystation12/Baystation12/pull/8119

**Comment by Glloyd** [comment]
Remind me to revert Bay Antag OOC before this is done: https://github.com/Baystation12/Baystation12/pull/8411

**Comment by Glloyd** [comment]
Also to revert this: https://github.com/Baystation12/Baystation12/pull/8527

We have the colour changer and the saturated sprites in this PR just look bad.

**Comment by Glloyd** [comment]
Add Paradise's pref option for the heartbeat in space: https://github.com/ParadiseSS13/Paradise/pull/590

**Comment by Glloyd** [comment]
I'll have to re-revert some of the Syndicate > Mercenary stuff too. Here is a list of files affected:

datums/mind.dm - Syndicate and Vamp stuff removed
gamemodes/autotraitor/autotraitor.dm - https://github.com/UristMcStation/UristMcStation/commit/35d440f22d3a1a7ff6fcf8656f6b221c79576e55 and Syndicate naming < file was deleted, have to hunt down traitor code and make it Syndicate again.

Go through and change nuclear emergency to Mercenary (It's still syndicate though.)

**Comment by Glloyd** [comment]
things are coming along. as far as the map goes, it's down to just the area issues, which I'll do in the morning, then I'll take care of any misc compile issues that will pop up after getting the map going. As I go along replaceing paths, I'm doing them for all the maps at once, so it won't take much longer for me to clean up the rest of the awaymaps/eventmaps/etcmaps. After that, I'm going to start porting some stuff over from my bay dev branch in a piecemeal fashion over the next week and a half while also working on some of those issues from up in the thread. @scrdest if you could make a note of anything that was removed or disabled in your PRs that needs to be brought back in, that would be awesome. Either that or do it in a PR.

Goal for tomorrow is to get the thing compiling and the maps working, as while as fixing some minor things I noticed that aren't up in the thread here. I'm optimistic, we might be able to do this by mid January.

**Comment by scrdest** [comment]
It's sorta messy, as a changelog-cum-TODO list written stream-of-consciousness and as I go from each of my commits and notice stuff that needs work.

- [ ] SVD, Knight, Energy Pistol for full compatibility with guncode changes/desired behavior
- [ ] Check all the other Urist guns and adjust as necessary for desired behaviors; hunt down any procs running on snowflakes that are now genericized.
- [ ] Vampire end-of-round report done? Test Vamp extensively, anyhow, especially mid-round additions and other refactor functionality and the two replacement powers.
- [ ] Custom lighters restored properly?
- [x] Russian revolver in the jungle crates axed (no longer exists in code)
- [ ] Blueshield armor (and SCOM armor using it) removed, replaced with storage/vest/heavy tentatively.
- [x] Thralldom axed
- [ ] Vamp icon removal done?
- [ ] Horde behavior (check_horde proc; just returns 0 for now) commented out, might need restoring.
- [ ] Check values for the max_combined_w_class -> max_storage_space changes; they were NOT changed, only adjusted the vars' names.
- [ ] Check if genetic power spells shouldn't be a genetic spell subtype.
- [ ] Maybe restore our who.dm's functionalities.
- [ ] Check all the copypasta'd light amount checks in the new system. Maybe proc them properly.
- [ ] Considering grown.dm got eaten by the daemons lurking in the Merge, check if other hydro code wasn't chewed on.
- [x] Removed the tile from the Smuggler's Satchel - in part due to laziness, in part because if you want to hide it, you will remove one *from the actual floor* anyway.
- [ ] Check if the BS12 changes make the SCOM whatchamacallit rig's mask still be spaceworthy.
- [ ] Maybe restore Ravensdale borg sprites.
- [ ] Check if Urist spells still recharge properly under the new system without revert_cast calls.
- [ ] Syndicate, are you there?

**Comment by Glloyd** [comment]
Cool. I'm going to go through the map and my stuff before touching that, so that way we can each work on something without getting in the way of the other. I'll also do the guns because one of my projects touches on them.

**Comment by scrdest** [comment]
[I just realized I could share a OneTab group of links with a bunch of relevant Bay commits.](http://www.one-tab.com/page/o97LET0_S4ao8TX9ovSTRQ)

**Comment by scrdest** [comment]
That's about all things I definitely wanted checked with the code itself done, the rest is either optional (as in, will deal with upon being asked to/if it comes up in testing) or requires actual playtesting.

**Comment by Glloyd** [comment]
that fixes the map

**Comment by Glloyd** [comment]
not much left now

**Comment by Glloyd** [comment]
@scrdest github fucked up your comment and i think unchecked some stuff. Anyways, I'd like to get what's left done over the next couple days. If you're free, we can get this done even faster. Map works now, and i fixed a lot of hte runtime errors.

**Comment by scrdest** [comment]
Fukken A. :+1: :heavy_multiplication_x: :100:

Let's get this shit tested!

**Comment by scrdest** [comment]
Live testing issues:
[ ] Maze awaymap throws runtimes, 'Undefined variable /obj/structure/maze/diamond/var/teleport_z,'

**Comment by Glloyd** [comment]
The maze thing is something I caused last night. When I get out of class, I'll fix that, same with the mentors.txt and the docking tag. Then I'm gonna go trough and change del to qdel then go through my own lists.

**Comment by Glloyd** [comment]
Figured out the id issue. With req_access_txt, having the value at zero meant all access. In the conversion to the list, it kept the zero for some doors, so i'll do a mass replace in notepad for that.

**Comment by Glloyd** [comment]
@scrdest getting real close. That may be all I'm doing tonight, so if you have anything to push that i haven't done yet, push it. Otherwise, we'll finish this off tomorrow.

**Comment by scrdest** [comment]
Damn. You ninja'd me on some stuff.

**Comment by scrdest** [comment]
Did you perchance do something to your branch? I can't seem to be able to push to it.

**Comment by Glloyd** [comment]
Oh, you'll have to PR it because it's my branch and not Urist's.

**Comment by Glloyd** [comment]
added you as a collaborator, push away.

**Comment by scrdest** [comment]
Didn't have to before. And now it just... worked.

**Comment by Glloyd** [comment]
Weird...

**Comment by Glloyd** [comment]
since we did push some of the same stuff, make sure neither of our things were eaten.

**Comment by scrdest** [comment]
I pretty much just resolved everything as either yours, if you removed the //qdels and didn't touch anything else, or mine if I've changed the functionality. Diff says only non-modify change is adding mentors.txt

**Comment by Glloyd** [comment]
Alright, cool. I'm going out for dinner, so I won't be touching this for a while if you can do anything more.

**Comment by scrdest** [comment]
Oh yeah, should've put those in the commit desc; updated the config to Bay, didn't touch anything we had, what I added I changed by my own judgement - starlight to add some sense to vamps cannot into spess, adding antags mid-round because fun allowed, and made biting people regen vampires' blood, since it's quite an obvious assumption it would for the player.

Genetics powers I changed are broken, those I didn't touch work fine - go figure -_-

**Comment by Glloyd** [comment]
oh, before i go. can you double check the heartbeat toggle? It wasn't working for me.

**Comment by scrdest** [comment]
Maze still throws two runtimes, cannot create objects of type null, thrown by the two teleporters at 17 & 18, 39, 7, and another of division by zero by glowshrooms at 22,57,7 thrown by New()ing them.

**Comment by scrdest** [comment]
Heartbeat toggle works fine for me.

**Comment by scrdest** [comment]
One of the awaymaps seems to be locking up DD outright. It's not beach, blackmarketpackers, or the maze, it might be Station_collision - I edited the former to qdel some object, though, or the challenge.

**Comment by scrdest** [comment]
Aside from the remaining maze runtimes and the merc shuttle controller (and maybe the vamp Turn power - it requires a mind in the target, and trying to hack one into the mob bypassed the checks, but runtimed, so I can't test it alone), the code is stable.

I suggest that after fixing all that, we merge it immediately. The engine (unless it plain doesn't work as-is, which I doubt but didn't check), the easels and the rest are not gameplay-critical, and seeing that schedule-wise the pooch is screwed so hard it's actually a lineage of pooches, each as screwed as its ancestors, it's the least we could do for the playerbase.

The features can be done just as well in a separate PR, and it will make reviewing them a fair bit friendlier on the GitHub list of changes, and the mapping changes in particular can be delegated on some of our mappers.

**Comment by Glloyd** [comment]
Fair enough. I do need to remap the entire engine though, because it won't work as is.

**Comment by Glloyd** [comment]
Also the update icon stuff. Urist inhands weren't working, nor were things on the back or ties.

**Comment by scrdest** [comment]
I can look into the icon stuff. It's probably the same kind of hook as I made for uristantags that got erased somewhere and I'm good with the logs and history-combing, but I didn't really delve into advanced mapping, so I'd rather not touch the engine if I can help it.

**Comment by scrdest** [comment]
Re: Urist inhands; BS12 introduced a system that allows manual specification of an icon for on-mob icons as a list specifying an icon used when held in that slot; currently L/R hand only. This means urist_only could eventually be deprecated for those purposes, currently doing a hackaround.

**Comment by Glloyd** [comment]
That's good, I've been slowly deprecating urist_only as BS12 adds more
icon_overrides to things. At this point, I think it's only still needed for
ties, But I'll have to take a look at update_icons code again later.

On Mon, Feb 1, 2016 at 1:00 PM, scrdest <notifications@github.com> wrote:

> Re: Urist inhands; BS12 introduced a system that allows manual
> specification of an icon for on-mob icons as a list specifying an icon used
> when held in that slot; currently L/R hand only. This means urist_only
> could eventually be deprecated for those purposes, currently doing a
> hackaround.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/pull/277#issuecomment-178098193>
> .
>



-- 
Graham Lloyd

**Comment by scrdest** [comment]
I just did. At first I added the item_icons to everything, which merrily did nothing at all even though manually varediting them to the correct icons file (or rather, the left hand one, the right hand proved obstinately un-editable) made the icons display properly. So I tried adding item_state_slots. Which walled me with undefined procs.

So, if you're gonna be doing this, you probably might as well add an if(urist_only) proc and just set it to what it should be on runtime, because doing this otherwise, especially if you don't know if it will work, is a painful waste of life.

**Comment by Glloyd** [comment]
that should be everything we need before it going live on the server. I'm going to do a quick test tomorrow after class though just to make sure it's all in proper shape.

**Comment by Glloyd** [comment]
One huge priority either tomorrow or after it goes live is reverting the changes to chem that make it so you have to refill it.

**Comment by scrdest** [comment]
Honestly? I was way against it, but I found out you can adminspawn *any* chemical to make it refillable. Might be worth to just clone the old-code machine and plop it on the map instead.

**Comment by Mark9013100** [comment]
On Polaris, the chem cartridges refill on their own.

**Comment by scrdest** [comment]
Might be a good way to deal with this too.

**Comment by scrdest** [comment]
Polaris PR for reference https://github.com/PolarisSS13/Polaris/pull/570

**Comment by Glloyd** [comment]
Get ready

**Comment by Glloyd** [comment]
Fuck, hurry up Travis

**Comment by Glloyd** [comment]
Badda boom badda bitch

**Comment by scrdest** [comment]
DUN DUN **DUN**

**Pull request merged**
