### PR TITLE
feature: Bluespace Revenants!

### PR DESCRIPTION
**Pull request by scrdest**
A new gamemode/antag. BSR for short.

image

Rodrigo here is something called a Bluespace Revenant.

Lore-wise, this is very flexible, but he's basically a walking, talking Anomaly.
Generally, it's someone who either had a run-in with either silly space magic nonsense, or did not maintain his Gellar field generators properly and fell into hyperspace or whatever.

The handwaveyness is very much relevant - because the exact nature of what a BSR is and does is generated based on tags; so it's almost a roguelite antag.

There's three core design concepts to them: **Powers**, **Hungers** and **Distortions**:

- **Distortion** plays the role of an IC objective. A BSR is a little bit unreal, and they glitch reality out just by existing like a source of radiant (and even worse with Powers). This is bad for them and bad for the crew, because all sorts of nonsense will start happening if they hang out in one spot for too long.
- **Hungers** are a counter to Distortion. It's some weird need that, if indulged, suppresses Distortion. This can be anything from eating bits of the station, through Great Value cult runes, to drinking blood
(because this originated as a full rework of Vamp and in fact you can force generation of a BSR-flavored Vamp)
- **Powers** are your stock extra abilities. The only quirk aside from procgen selection is that their cost is generally surplus Distortion.

The whole point of this exercise is to make this antag as hard to make boring as possible.
If you stealthantag too long, Distortion will build up and make you increasingly obvious.
To avoid that, you need to go and engage with the round. Win.
You can peaceantag, but your very existence messes things up, so there's still a conflict.

### CODE REVIEW

**Comment by Glloyd** [comment]
Seems very cool. I won't have a chance to look at this for a couple days, but maybe if you think it's ready for it, sometime this weekend we can run it on the server as a sort of open test for it.

**Comment by scrdest** [comment]
> Seems very cool. I won't have a chance to look at this for a couple days, but maybe if you think it's ready for it, sometime this weekend we can run it on the server as a sort of open test for it.

Would be pretty awesome; I could definitely use some feedback on the balance, because it's a bit tricky to figure out - the Distortion mechanics rely on the antag staying in one place for a while and it's hard to estimate what's a reasonable delay before reality starts going haywire.

**Comment by scrdest** [comment]
Should be good to go, for a first pass anyway. Made best effort at balancing this out and testing/fixing anything I could think of.

Depending on feedback, I might integrate the rates/costs/etc to a Config system to make this tweakable without recompiling.

**Comment by Glloyd** [comment]
The server is running this branch for the night. I won't be around until later, but you can ping me on discord if anything server-related comes up in the meantime.

**Comment by scrdest** [comment]
This is not abandoned, continuing development off of the Baymerge branch for now.

**Comment by Glloyd** [comment]
merged into baymerge-testing in #1146

**Pull request closed without merging**
