### PR TITLE
Ore and gun bugfixes

### LINKED ISSUE #1306: Mining drills dont seem to extract gold or silver
### Description of issue

Mining drills only seem to extract platinum from precious mineral deposits

### Difference between expected and actual behaviour

_No response_

### Steps to reproduce

set up drill
significant precious mineral deposit
look inside
only platinuim

### Specific information for locating

_No response_

### Client version, server revision, & game ID

current as of time of report

### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

### LINKED ISSUE #1310: Top mount SMG still jams
### Description of issue

top mount smg from protolathe still jams when loaded with real ammo

### Difference between expected and actual behaviour

it should not do this

### Steps to reproduce

print smg, load with not rubbers, 3 round burst, jam

### Specific information for locating

_No response_

### Client version, server revision, & game ID

current as of oct 7 2023

### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

### PR DESCRIPTION
**Pull request by CPU-Blanc**
A few bugfixes.

- Guns with `jam_chance` of 0 no longer have a change to jam if you load it with ammo that it didn't originally spawn with (Fixes #1310 )
- Corrects ore noise map generation to actually use the map index rather than itself, causing every tile to generate the rarest ores, preventing surface or mid level ores from generating. Thanks to @scrdest for helping figure this one out! (Fixes #1306 )
- Reverts some regressions introduced in #1250 as well as correcting some odd changes. Mined rocks now once again generate ore for the tile underneath.

### CODE REVIEW

**Comment by Glloyd** [comment]
this will conflict with #1315 as a heads up

**Comment by CPU-Blanc** [comment]
> this will conflict with #1315 as a heads up

Already speaking to scr over it. That commit has already been cherry-picked into here so there shouldn't be any issues

**Comment by scrdest** [comment]
> this will conflict with #1315 as a heads up

This IS #1315 and two other commits in a trenchcoat honf

**Comment by CPU-Blanc** [comment]
Gonna poke @ggermanicus as he last touched mining. Let me know if I've reverted something you've done for a reason

**Comment by Glloyd** [comment]
i'll wait to hear back from grant, and if all is good i'll merge this

**Comment by ggermanicus** [comment]
looks good to me

**Pull request merged**
