### PR TITLE
Another fix

### PR DESCRIPTION
**Pull request by JacobLee1**
Fixes the incredibly important issue of the homogeneous folders in IA. There's now a red, blue, yellow, and white folder instead of four blue ones. Gllerd is a ninja and pulled my PR before I could get this pushed.

### CODE REVIEW

**Comment by Nienhaus** [comment]
Gllerd= Glloyd+nerd?

**Comment by Nienhaus** [comment]
Oh, also :+1: x :100:

**Comment by Glloyd** [comment]
:+1:

**Comment by scrdest** [comment]
Not the hero we deserve, but the hero we need right now, right here.

**Pull request merged**
