### PR TITLE
Flashlight  Subtypes (Flares, Glowsticks,  Lanterns, Penlights, Flashdarks, Lamps) now have action buttons.

### PR DESCRIPTION
**Pull request by Yantarii**
image

Emergency Flares and Glowsticks now have action buttons to ignite/snap them.
Pressing them again will just inform the user in chat that it's already ignited/in use.

### CODE REVIEW

**Comment by Yantarii** [comment]
Lanterns, Penlights, Flashdarks and Lamps now have their own specific action button text.

**Comment by CPU-Blanc** [comment]
I don't really see why the glowstick & flares would need a dedicated action button, given they are single use?

**Comment by ErrorsWindows** [comment]
you squeeze the pocket that has the glowstick in it with your hand to crackle it instead of having to take it out

**Comment by Yantarii** [comment]
Going to adjust flares and glowsticks to have a button only when unlit to activate them.

I would prefer to keep subtypes of objects/devices consistent UI wise, I think single-use button prompts aren't going to cause much of an issue screen-estate wise.

**Comment by Glloyd** [comment]
> Going to adjust flares and glowsticks to have a button only when unlit to activate them.
> 
> I would prefer to keep subtypes of objects/devices consistent UI wise, I think single-use button prompts aren't going to cause much of an issue screen-estate wise.

If you made this change I'd be fine merging this

**Pull request closed without merging**
