### PR TITLE
Baymerge to March 11th, 2019

### PR DESCRIPTION
**Pull request by Naxodile**
Only a little late.
- [x] Medical needs the new equipment (auto-cpr, body scan displays, heating/cooling elements) added
- [x] There's now a functional BSA that acts as a ship weapon and is used for mining if you're insane.
- [x] The Trajan needs a full set of ship computers and machinery, this is already in the current commit
- [x] Re-add missing crafting recipes
- [ ] Re-add mentors
- [x] Fix missing locker appearence datums for first & second officer
- [x] Fix req_access uses in **every single map**
  - [x] ~~Fix req_access for Glloydstation~~ -Not a priority at the moment
- [x] Possibly revert the ammo caliber consolidation
- [x] Remove the delay before the pregame countdown
- [x] Initialization time has somehow doubled to near 400 seconds in my local tests
- [x] Find the source of the random crashes?
- [x] ~~Giant spiders aren't compatible with our hostile mob system.~~ 
  - They still produce some strange behavior, but it's at least functional
- [ ] Fix the admin body scan report runtime.
  - The cause of this is still unknown, there's not much debugging information from it
- [x] Add in the new ballistics sprites.
- [ ] Adjust the new Travis tests to our maps.
- [x] Repaths are needed for all our templates, particularly the NT Trading Station.

### CODE REVIEW

**Comment by Glloyd** [comment]
As I mentioned on Discord, I'll be able to help you out with this after this week. I imagine there might be some stuff I'll need to hunt through to add back in as well. Also, you must have overwrote our travis defines, you've got Bay's maps in Travis right now.

**Comment by Glloyd** [comment]
@Naxodile i've started work on updating this to current urist, working through that big list of conflicts. do you have a more extensive list of the work we need to do on the merge (i.e. changes to revert, stuff to add back in) or is that it?

**Comment by Naxodile** [comment]
Updated it with everything I had found.

**Comment by Naxodile** [comment]
This was merged already. @Glloyd thoughts on finally merging baymerge-testing into master now? We aren't exactly testing it anymore

**Comment by Glloyd** [comment]
Yeah, once I sort the ci testing out, I plan on finally merging to master.

**Pull request closed without merging**
