### PR TITLE
This kills the Thaler

### PR DESCRIPTION
**Pull request by Knoxon**
Removes Thalers, replaces with muh generic sci-fi credits.

### CODE REVIEW

**Comment by Glloyd** [comment]
rip thaler, rip spacecash

**Comment by scrdest** [comment]
Eh, personally, I'd rather keep the thaler specifically because it's non-generic. I feel that could use a player poll or something.

**Comment by Nienhaus** [comment]
I live you. I want my space credits.

**Comment by TGameCo** [comment]
We should make a urist-specific currency

**Comment by scrdest** [comment]
☼s when?

**Comment by Nienhaus** [comment]
No please @TGameCo I wanna play my generic space game.

**Comment by Glloyd** [comment]
Yeah, make a 3 day poll on the server for this Knox. We don't want to be like Bay and just rename things willy nilly, support or no.

**Comment by Glloyd** [comment]
polls up, there's five options.

**Comment by Glloyd** [comment]
Cannot automerge. This is due to #205

**Comment by Knoxon** [comment]
I might have to close this, github is freaking the fuck out and won't let me push the commits to my repo.

**Comment by Knoxon** [comment]
Yeah, my github is shitting itself, someone else can take this over

**Comment by Glloyd** [comment]
Well, credits won, so I guess I'll do this.

**Pull request closed without merging**
