### PR TITLE
Skrell Terrorist Base Template

### PR DESCRIPTION
**Pull request by scrdest**
Adds an underground Skrell Terrorist base template. 

This is a rather hard map as far as looting is concerned - this is an active base, not a ruin, and it is protected accordingly, but has the loot to match - especially if the prospective raiders are determined enough to break open the safe, and once cleared it's able to hold air (for a while).

### CODE REVIEW

**Comment by Glloyd** [comment]
Pic? And once this is in I'll enable underground map spawning because we'll have a good enough variety.

**Comment by scrdest** [comment]
I have some weird-ass icon issues ATM for unclear reasons, probably because DM a shit.


skr1
skr2
skr3
skr4

**Comment by Glloyd** [comment]
Did you spawn it manually or use the template spawner? If the latter, I
know why. If the former, I'm not sure, I'd have to check it out locally.

On Sun, Apr 17, 2016 at 7:00 PM, scrdest <notifications@github.com> wrote:

> I have some weird-ass icon issues ATM for unclear reasons, probably
> because DM a shit.
>
> [image: skr1]
> <https://cloud.githubusercontent.com/assets/4363639/14590664/c6733792-0500-11e6-98bb-ccc91c2c4f89.png>
> [image: skr2]
> <https://cloud.githubusercontent.com/assets/4363639/14590663/c672ee72-0500-11e6-868d-88dc7d9dceb0.png>
> [image: skr3]
> <https://cloud.githubusercontent.com/assets/4363639/14590665/c674986c-0500-11e6-83aa-084b05645c7b.png>
> [image: skr4]
> <https://cloud.githubusercontent.com/assets/4363639/14590662/c66bfd74-0500-11e6-9205-09af2ea91dd7.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/pull/444#issuecomment-211126314>
>



-- 
Graham Lloyd

**Comment by scrdest** [comment]
Yeah, I did. It damaged the doors too for some reason.

**Comment by Glloyd** [comment]
HOW HAS IT BEEN 15 DAYS SINCE THIS WENT UP.

**Comment by Glloyd** [comment]
Figuring out what was wrong with this helped me figure out infestation being fucked up. It was spawned midround so it didn't initialize certain machinery and structures properly. Gonna merge it, and when I get underground template spawning working, it'll be fine in game. I'll have to make a system for the Infestation map though.

**Pull request merged**
