### PR TITLE
Using a scope is now a dedicated hotkey - [CTRL + T]

### PR DESCRIPTION
**Pull request by Yantarii**
You can now unscope/scope without having to right click your weapon and go through the right click menu. This makes using scoped weapons not a test of how fast you can click Byond's awful menus.

I chose CTRL + V since it's close to the homerow and is easy to press quickly.

### CODE REVIEW

**Comment by Yantarii** [comment]
Ideally we could have some sort of mappable keybind once Bay finishes that PR off for it.

**Review by CPU-Blanc — CHANGES_REQUESTED** [review]
As someone who likes to use copy-paste hotkeys, this seems like a poor choice :P
Could we change it to something that isn't a global hotkey already?

**Comment by ErrorsWindows** [comment]
normally i use the button in the object menu in the top right but this works too

**Comment by Yantarii** [comment]
Adjusted to CTRL + T, as it isn't used anywhere

**Review by CPU-Blanc — APPROVED** [review]

**Pull request merged**
