### PR TITLE
SCom money fix (?)

### PR DESCRIPTION
**Pull request by scrdest**
Possibly fixes researching objects not giving money.

### CODE REVIEW

**Comment by Glloyd** [comment]
Didn't I commit this already?

**Comment by Glloyd** [comment]
https://github.com/UristMcStation/UristMcStation/commit/a9f25cbbe7912ce627c1e5fd0720ab83cdbd3972

**Comment by scrdest** [comment]
...I thought I replied to that.

Anyway, I am fixing that very line :P This PR removes an indent - which may or may not be a problem, as it put that line under the else if(scomtechlvl < S.scomtechlvl) check, and also makes it update scommoney, not S.scommoney, as that's what seems to control the funds in every other check, including on money display.

**Comment by Glloyd** [comment]
That commit already removed the indent, that's why you can't merge. Also, it's supposed to be S.scommoney in this case.

**Comment by scrdest** [comment]
WTF? THAT WASN'T HERE YESTERDAY. I literally edited master in the online editor. I... what. WHAAAAT. I don't even.

**Comment by Glloyd** [comment]
Honk.

**Pull request closed without merging**
