### PR TITLE
Waistcoat as an accessory

### PR DESCRIPTION
**Pull request by Kydrasz**
If I did it right then the title is enough info. Seeing as I did this on my phone, I doubt it.

### CODE REVIEW

**Comment by Kydrasz** [comment]
Note to self: Remember to use wcoat instead of waistcoat

**Comment by scrdest** [comment]
Once you sort out the mapping errors, please test to see if equipping them on roundstart/admindress works. I know no accessory I'm aware of starts attached on roundstart currently.

**Comment by Kydrasz** [comment]
I'll re-do this once I fix the mapping errors.

**Comment by scrdest** [comment]
You don't need to close the PR to fix it, but your call.

**Comment by Glloyd** [comment]
It'd be easier to make a separate waistcoat as an accessory. Changing paths will break stuff with Bay pretty hard.

**Pull request closed without merging**
