### PR TITLE
Adds NT Mk58 to security lockers.

### PR DESCRIPTION
**Pull request by EyesNoEyes**
As well adds a custom NT Mk58 to HoS locker

### CODE REVIEW

**Comment by scrdest** [comment]
Replaces the epistol HoS had. Otherwise, tentative :+1: . @Glloyd, what's your take on that?

**Comment by Glloyd** [comment]
All you're doing here is adding a pistol to the HoS's locker in place of the e-gun, what's the reasoning behind that?

**Comment by EyesNoEyes** [comment]
It's not just the HoS locker. I added standard Mk 58s to sec lockers so they'd go with the .45 mags that already spawn in them. My attempt at a sparse implementation of bulletsec.

The reasoning for replacing the egun in the HoS locker instead of just adding is that the HoS already has the custom energy pistol that starts on his desk, and the HoS locker starts with too many items already. Since there was a wood finished mk58 sprite available I figured it would make sense to give it to HoS.

**Comment by Glloyd** [comment]
for some reason that second part didn't show up. github is still shit on mobile apparently. i dunno about this PR. I'm gonna keep it on the backburner until the baymerge is done.

**Comment by scrdest** [comment]
Made redundant by #487

**Pull request closed without merging**
