### PR TITLE
[Ready!] adds medical patches.

### PR DESCRIPTION
**Pull request by chaoko99**
🆑 
Medical patches. They're like pills but slower, allowing more medicine to be used without risk of OD.
/ 🆑 

Y'know. Like TG.

### CODE REVIEW

**Comment by chaoko99** [comment]
cannot stretch enough: THIS DOESN'T WORK YET.

**Comment by chaoko99** [comment]
Oh, forgot: Credits to @Andromeda-K22 for doing most of the actual medpatch code, even if I did end up discarding a fair portion of it.

**Comment by chaoko99** [comment]
No actual chems use this. Waiting for this to be merged before I bother.

**Comment by Naxodile** [comment]
Conflicts, presumably no further interest, and no content in the PR itself.

**Pull request closed without merging**
