### PR TITLE
Chameleon gun fix

### LINKED ISSUE #326: Chameleon Gun does not use mags
The chameleon gun does not seem to use magazines. It still works but you have to empty the mag and load the bullets into the gun one by one which is weird, slow and makes it painfully awful.

### PR DESCRIPTION
**Pull request by liction15**
Fixes #326 

Please check the code to ensure this would actually work. I had to dig around and found the gun under chameleon clothing, not sure if that would affect anything. Mostly copied over what it seemed to be missing and edited it to what it should be.

### CODE REVIEW

**Comment by liction15** [comment]
okay it failed but Im learning it seems MAGAZINE needs to be defined

**Comment by scrdest** [comment]
Something's wrong, it shouldn't read MAGAZINE as a variable, it's essentially a stage direction for the compiler to replace the word MAGAZINE with a static number - in this case, 4.

I'd hazard a guess it's a silly problem with the compiler not reading the macro definition because the clothing module is read before the projectile.dm file with the definition, though I might be wrong.

Also, MAGAZINE load_type guns don't seem to need ammo_type defined, the magazine's vars cover that.

**Comment by Zuhayr** [comment]
````MAGAZINE```` is defined after this file is checked by the compiler, yep.

**Comment by liction15** [comment]
the only thing I could think of to fix this is to move the chameleon gun bit to where all the other pistols are.

**Comment by scrdest** [comment]
I'd edit that to simply load_mode = 4 and add a comment explaining you couldn't make it MAGAZINE because the file's read before the macro def.

**Comment by liction15** [comment]
yay it seems that it compiled correctly, I is real coder nao?

**Comment by scrdest** [comment]
Did you test it? 

If you didn't, you can edit the admin list in config to give yourself full priviledges, set up a local server with the Dream Daemon and spawn the gun and mag. Just don't commit the change for all that's holy. 

It looks good at a glance, but I know from experience porting guns to the new guncode can be a bit tricky to get right.

**Comment by liction15** [comment]
Alternatively we could port over the existing file that's on bay which seems to turn the gun into a energy weapon, although we will probably need to change the chameleon kit to not include the mags. In any case I don't really know how to set up a local server to test this myself right now, I can probably figure out that later though.

**Comment by scrdest** [comment]
It's pretty straightforward. Compile in DreamMaker (Build -> Compile), open Dream Daemon, enter the file path of the .dmb file, hit the green button, wait until it turns yellow (it may briefly hang on you), click it. Boom, you're in game on a local server.

**Comment by liction15** [comment]
Just finished testing it. I can confirm that the gun now comes with a magazine loaded and also can be loaded and unloaded like other guns.

**Comment by scrdest** [comment]
Alright then!

**Pull request merged**
