### PR TITLE
Too Spooky

### PR DESCRIPTION
**Pull request by scrdest**
More ghost spookiness with thin veil - ghosts can:
- appear on photographs (10% chance to not appear),
- knock on windows, 
- whisper into tape recorders 
- whisper to sleeping carbon mobs w/client (formatted as a normal dream).

Some hooking into native photo procs was necessary, but it's non-critical if it gets overwritten.

### CODE REVIEW

**Comment by Glloyd** [comment]
Spoopy

**Comment by scrdest** [comment]
You okay with that? I wanted to stage this 'cause it's a bit messy merge-wise and maybe balance-wise.

**Comment by Glloyd** [comment]
I can see the whisper being abused, but it's logged so I'm not too worried.

**Comment by Glloyd** [comment]
👍

**Pull request merged**
