### PR TITLE
Very quick washing machine fix

### PR DESCRIPTION
**Pull request by Vakothu**
Untested, but this is how Bay fixed components unable to be added to a washing machine in https://github.com/Baystation12/Baystation12/pull/33669

### CODE REVIEW

**Comment by Glloyd** [comment]
do we need the other fixes from that PR?

**Comment by Vakothu** [comment]
I have no idea if we do or not, I just grabbed as little of the code as possible to avoid any incompatibility that could result. We might wanna test it.

**Comment by Glloyd** [comment]
if they are issues we have, it's probably best to grab it all

**Comment by Vakothu** [comment]
Gonna close this and cherry pick that commit then.

**Pull request closed without merging**
