### PR TITLE
[REQUEST] Species locking the Skrellian hardsuits

### PR DESCRIPTION
**Pull request by liction15**
Does half of #430

### CODE REVIEW

**Comment by liction15** [comment]
ffff build failed species restriction is undefined arg.

**Comment by liction15** [comment]
I figured out what i did wrong I changed the wrong file for the RIGs

**Comment by liction15** [comment]
I ran a server to test the change I made to skrell hardsuits and i can now confirm that the change appears to be working as intended.

**Comment by liction15** [comment]
welp seeing as this is already on glloyd's todo list i guess ill close this for now.

**Comment by scrdest** [comment]
Eh, I don't see any reason to double the work.

**Comment by Glloyd** [comment]
I'll take a look at this tomorrow, should be good though.

**Comment by Glloyd** [comment]
Mind adding the restriction to the Unathi rigs on here?

**Comment by liction15** [comment]
I would if i could figure it out but I cant because unathi rigs seem to use a different path thus why adding species_restricted throws an undefined variable error.

**Comment by Glloyd** [comment]
Alrighty.

**Comment by Vakothu** [comment]
You'll probably need to put the species_restricted flag on the body of the Unathi rig, not the back-worn control panel.

**Pull request merged**
