### PR TITLE
Tape

### PR DESCRIPTION
**Pull request by TGameCo**
Upcoming PRs will be announced on my dev thread
http://prevess.com/viewtopic.php?f=4&t=121

Information:
*Easily expandable
*Each tape dispenser has 25 uses
*Can remove tape or cartridge
*Tape does nothing, at the moment, but I'll be adding things in the Tape-based weapons commit

Wait for the fixes commit to merge

### CODE REVIEW

**Comment by TGameCo** [comment]
Ye wot m8

**Comment by TGameCo** [comment]
Why ;-;

**Comment by Glloyd** [comment]
I thought this was on hold until you added tape weapons.

**Comment by TGameCo** [comment]
Just did, knifeplane and cargoplane

**Comment by TGameCo** [comment]
If you have ideas for more, just tell me. I don't have any more

**Comment by Glloyd** [comment]
Okay, but is that all tape is useful for? Knife plane and cargoplane? I'm sure there's more potential for tape than just that. Also, an idea for weapon. there was that makeshift shotgun from /tg/.

**Comment by TGameCo** [comment]
Makeshift shotgun?
Also, I was thinking of using tape as restraints

**Comment by Glloyd** [comment]
I'm on my phone so I can't really hunt it down right now, but /tg/ has an improvised shotgun.

**Comment by Glloyd** [comment]
Ask people on the server for ideas, you're bound to get at least a couple decent suggestions.

**Comment by TGameCo** [comment]
Ok, I'll do that. Our community is great at thinking of improvised weapons... I think...

**Comment by Glloyd** [comment]
Heh, yup. Don't just limit it to weapons. Maybe improvised tools or even just general uses for tape.

**Comment by Glloyd** [comment]
I've tagged this as something to be done before I ask Vac to update. Don't let me down @TGameCo

**Comment by TGameCo** [comment]
Gah. School just started up for me again. I'm actually going to be closing this so I can add more things. Don't let this hold you up.

**Pull request closed without merging**
