### PR TITLE
Updates Sport car to fit on the roads better.

### PR DESCRIPTION
**Pull request by Nienhaus**
http://i.imgur.com/WmjOf2k.gifv

### CODE REVIEW

**Comment by Glloyd** [comment]
would it still fit in hallways and with mobs though?

**Comment by Nienhaus** [comment]
5tcsvbq
Not an ingame picture but this is how it'd look ingame in a hallway.

**Comment by scrdest** [comment]
The width on north/south orientation bothers me. It's one-and-a-half tile wide visually, so it'll make steering it confusing. Wouldn't it be simpler to just make the actual road tiles fit better?

**Comment by Nienhaus** [comment]
Nienhaus: It would not be easier to edit the road tiles.
Nienhaus: http://i.imgur.com/TDuzSdd.png
Nienhaus: It would be a fairly long process editing sprites that I didn't even make.
Nienhaus: You will almost almost never see it on normal tiles
Nienhaus: It's for roads.
I should note this is my opinion.

**Comment by Nienhaus** [comment]
@Glloyd Merge please so I can make a new PR

**Comment by scrdest** [comment]
@Nienhaus You might want to start using branches for future PRs if you know how, that gets rid of exactly this problem, if you don't I can guide you through that on Steam if you want.

**Comment by Nienhaus** [comment]
@scrdest I know how to but Glloyd told me I never had to so I haven't.

**Comment by Glloyd** [comment]
you don't have to, but it is useful in situations like this where you want
to do two things but i don't have reliable intenert access

On Sat, May 23, 2015 at 11:09 AM, Nienhaus <notifications@github.com> wrote:

> @scrdest <https://github.com/scrdest> I know how to but Glloyd told me I
> never had to so I haven't.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/pull/228#issuecomment-104908720>
> .
>



-- 
Graham Lloyd

**Comment by Glloyd** [comment]
:+1:

**Pull request merged**
