### PR TITLE
[WIP][DMN] Ship AI Overhaul

### PR DESCRIPTION
**Pull request by Andromeda-K22**
The goal of this PR is three things:
1. Add name generation for AI overmap combat ships, based on faction.
2. Add random personalities for AI overmap combat ships, based on factions.
3. Add in-combat taunts triggered by various events. 

Personalities should ideally govern retreating from combat, jumping out, etc! 

Anyone else is of course free to contribute to this, and I welcome assistance given some of this may be over my head.

### CODE REVIEW

**Comment by Glloyd** [comment]
I love this. This is kind of where I wanted to go with the naming, which is why the designation var and the ship_category var exist under the overmapship mob. This could hook into that, the idea was for it to eventually be name = "[designation] [name] - [ship_category]"

So - "NMV Icarus - NanoTrasen Fast Attack Vessel"

**Comment by Glloyd** [comment]
You've still got some compile issues

**Comment by Andromeda-K22** [comment]
Yeah, am aware. This isn't done yet so it's no biggie.

**Comment by Andromeda-K22** [comment]
Going to be pushing final changes shortly. Unfortunately I don't really have the energy to work on this and develop AI code, but the basics are here for anyone who wants to pick this up at a later date.

Ship name picking is in, though.

**Pull request closed without merging**
