### PR TITLE
Atmospherics Overhaul

### PR DESCRIPTION
**Pull request by Andromeda-K22**
Torchmos was okay. But it could be much better.

+A second level to atmospherics!
+An airmix tank. Finally.
+Centralized computer room for atmos tanks and monitoring.
+Another atmos and engineering voidsuit, and locker.
+Engineering lockers increased to 4, atmos lockers increased to two.
+Various minor changes to atmospherics layout.

-Aft Starboard solar array. Your sacrifice shall be remembered.
Lower Atmos:
https://cdn.discordapp.com/attachments/235284149286469632/590079957036695563/unknown.png

Upper Atmos:
https://cdn.discordapp.com/attachments/235284149286469632/590080044374818818/unknown.png

### CODE REVIEW

**Comment by Glloyd** [comment]
i'll make comments on this tomorrow

**Comment by Glloyd** [comment]
I like it, it needs a few changes though, I'm marking up those images with some remarks and suggestions

**Comment by Glloyd** [comment]
Okay, this is what I've got.

I'm sorry.

unknown (2) - mockup

unknown mockup

**Comment by Andromeda-K22** [comment]
I don't see a reason to put the atmos control room on it's own APC.

**Comment by Andromeda-K22** [comment]
image
image
@Glloyd

**Comment by Naxodile** [comment]
Almost certain this PR's going to remain in the graveyard with its conflicts. @Glloyd you can consider taking the (presumably) updated version of this from AFCUV Pluto if interested.

**Comment by Glloyd** [comment]
Yeah, the conflicts + outdated nature of this has made it an issue. It's on my list to recreate this on the current build, but I haven't gotten to it yet.

**Pull request closed without merging**
