### PR TITLE
Adds Pirate Gantry Vessel

### PR DESCRIPTION
**Pull request by Yantarii**
## Content
- Adds a Pirate Gantry vessel as a new ship on the overmap.

Pirate Gantrys are makeshift-vessels made from escape-pods and scrap, with a few small hardpoint to shoot from and poor safety regulations. A decent ship to practice captain-ing, or a quick boarding for the ICS Nerva crew.
StrongDMM-2024-04-20 20 37 38

Ghosts can join as pirate defenders if boarded, enjoy the small-scale CQC.

### CODE REVIEW

**Review by CPU-Blanc — CHANGES_REQUESTED** [review]
This template isn't actually being loaded in. You'll need to add it to `config/shipTemplates.txt`

**Comment by Yantarii** [comment]
Going to do some quick tests, but after that, should be good if it's all approved.

**Comment by CPU-Blanc** [comment]
Just checking in. Did you ever do whatever tests you needed to?

**Comment by Yantarii** [comment]
Nah not yet, been busy with work

Having difficulty testing ships as I'm not engineering minded and don't actually know how to setup the nerva engine for thrust haha

**Comment by CPU-Blanc** [comment]
Debug > Show debug verbs > Start SM > H2. Then set the pressure regulator to like 1,500kpa. That'll get you going c:

**Comment by Yantarii** [comment]
> Debug > Show debug verbs > Start SM > H2. Then set the pressure regulator to like 1,500kpa. That'll get you going c:

Thanks! I'll try to get some test dones on Saturday and hopefully we are good then

**Comment by Yantarii** [comment]
Did some testing, works to engage and such, should be good to test live

**Comment by Glloyd** [comment]
Merging it so we can spawn it in and mess around with it. Shouldn't be any issues though, and we can probably add it to the pirate station spawn list without any issue.

**Pull request merged**
