### PR TITLE
Spoopy Mobs. SIMPLE MOB ATTACK SOUNDS WHICH SHOULD HAVE BEEN LIVE SINCE FOREVER.

### PR DESCRIPTION
**Pull request by scrdest**
Adds four new hostile simple_mobs for spoopy admin fun/events/awaymaps, inspired by a certain round of brainless-person-revival antics: 

Zombies, a basic weak-ish one with awful myopia when idle and a tougher variant that cannot be killed by normal measures as they will regenerate from death, Cata: DDA style, intended for survival-style rounds where people are supposed to evade them, not eliminate them. Both are slow enough to be easily outrun, but fast enough to be a threat when aggro'd.

zombies

Vampires, which are just your basic, pretty tough simple_mobs with a somewhat amusing attack_sound, with a subtype for another sprite. Any resemblance to characters, fictional or real, is purely coincidental, donut soo.

vampsms femvampsms

And yeah, the skin tone is intentional.

Finally, in testing I noticed a really odd oversight in the hostile mob code - somehow, for three years, nobody noticed that attack_sound var does absolutely nothing, and as such simple_mob melee attacks are completely absent. HONK. A single playsound rectified that loooong-standing issue.

### CODE REVIEW

**Comment by Glloyd** [comment]
I recognize that player sprite. Honk. :+1: if you move the icons to the uristmob folder. I'd say fold in bat.dmi and just create a simplemob.dmi. Don't forget to change the bat ones in the file as well if you do that.

**Comment by scrdest** [comment]
Will do, just gotta do one last test and push of another PR.

**Comment by Glloyd** [comment]
Ya broke it

**Comment by Glloyd** [comment]
you forgot to commit simplemobs.dmi

**Comment by scrdest** [comment]
I know, just took me some time to force git to cooperate in committing it now.

**Comment by Glloyd** [comment]
perfect/10

**Pull request merged**
