### PR TITLE
Research wing remap (Adopted #1329)

### PR DESCRIPTION
**Pull request by CPU-Blanc**
Adopted from Yulisa's now abandoned/stale PR (#1329). Major credits for the work to them.

For now, all I've done is fix the nerva-1.dmm formatting to use the map merge tool, and rebased onto our current baymerge-testing head. Please do look out for any regressions, as this was an utter headache to both get up to date and convert, especially the cloning bay, as a lot of conflicts were there.

If Yulisa returns and wishes to resume work, I'm happy to hear their input, and/or they can open PRs to my fork to continue contributions to the remap.

Todo:

- [x] Implement changes requested in the original PR
- [x] Fix failing unit tests

### CODE REVIEW

**Comment by Glloyd** [comment]
bunch of failing tests, mostly related to disposals issues

**Comment by CPU-Blanc** [comment]
Yep. On my todo's. I can already see why

**Comment by Glloyd** [comment]
if this gets finished i can set up a playtest at some point

**Comment by CPU-Blanc** [comment]
All good for review & playtest @Glloyd ! Finally.. :sweat_smile:

**Comment by CPU-Blanc** [comment]
Yet another poke @Glloyd 
Can rebase when you're ready for a test play

**Pull request merged**
