### PR TITLE
Adds toeless jackboots to Xeno and Sec wardrobes

### PR DESCRIPTION
**Pull request by EyesNoEyes**

### CODE REVIEW

**Comment by scrdest** [comment]
I don't see a reason to put them in Xeno wardrobe. It has an actual gameplay effect (damage against downed targets increased), and is equippable by anyone, so people might steal them as non-Unathi just for that.

That said, it's as easy to get the jackboots via loadout.

**Comment by EyesNoEyes** [comment]
Right. I understand. I figured it would make little difference considering, as you mentioned, you can start with it, and just wanted to increase the number that were available on the station for those that were unfortunate enough to lose theirs, since it was impossible to acquire them any other way beyond prayer..

**Comment by Glloyd** [comment]
@EyesNoEyes take the jackboots out if the Xeno locker and I'll merge it.

**Comment by EyesNoEyes** [comment]
Done

**Pull request merged**
