### PR TITLE
Mapping Update on Small Pirate Vessel

### PR DESCRIPTION
**Pull request by Yantarii**
image

- Adds more lights, as it's very difficult for boarders and pirate defenders to see to see, mostly small lights and a few large ones.
- Decal pass for more detail.
- A bunch of pirate coats and uniforms, yarr
- Small medbay next to cryo storage, with a stethopscope, basic surgery and medical gear, more loot for people boarding to steal.
- Moves bathrooms north, near cryo.
- Adds a Vault to the pirates where they store precious minerals and money, to make it more worthwhile actually boarding them.

The intention is to encourage more boarding and looting of vessels, quickly while they are attacking the ship. There's a stethoscope found in the pirate vessel if someone has forgotten to bring one, and a bunch of coins and guns if people don't want to crack the safe. A small medbay has been added so pirate defenders have a slim chance of minor healing before the crew kill them.

### CODE REVIEW

**Review by CPU-Blanc — APPROVED** [review]

**Comment by The32bitguy** [comment]
I recall being unable to access the vendors on the Pirate Vessel as a Pirate Ghost role. Unsure if you would want to address this within the scope of this PR.

**Comment by Yantarii** [comment]
> I recall being unable to access the vendors on the Pirate Vessel as a Pirate Ghost role. Unsure if you would want to address this within the scope of this PR.

Thanks for letting me know, I'll hack/emag them as Boarders don't have IDs anyways, plus they are pirates

**Comment by Yantarii** [comment]
Fixed.

**Review by CPU-Blanc — APPROVED** [review]

**Comment by Glloyd** [comment]
thanks for updating this old map.

**Pull request merged**
