### PR TITLE
Chemical Lab Away Mission - |WIP|

### PR DESCRIPTION
**Pull request by Yantarii**
**WORK IN PROGRESS | DO NOT MERGE | -**

Reworking old PR - https://github.com/UristMcStation/UristMcStation/pull/920

## Chemical Lab Away:
**1st Z-Level:**

**2nd Z-Level:**

## Information:
- Players in this role are not antagonists, but are free to defend themselves should they be boarded, or hostile action is taken against them, similar to other aways.

- This adds a chemical laboratory, hidden on an asteroid, as a spawnable away mission.
The intention of this Away is to allow for players to have a playground to experiment with chems, virology and botany away from the station, while also providing a valuable incentive to investigate and claim weaponry, exotic chemicals and fun viruses from the labratory, and open interesting RP interactions.

- Random Chemistry Shelves - Akin to System Shock 2, each round will have random chemicals spawn on shelves, these can range from boring to !!!FUN!!! things, incredibly dangerous/round changing chemicals (Xenomicrobes, etc) will have an incredibly low chance to spawn each round, but to still be interesting if the RNG Gods do approve. (Somewhere around every 50/100 rounds seems fair with current population)

### Jobs:

**Lab Supervisor**
- Acts as a Warden and Leader of the Labratory, equipped with a small brig, should things get out of hand, and an armory should boarding occur. They can assist the workers if they see fit. While the Supervisor has total control over the lab workers, harming and general shittery should still be punished, unless within reason.

**Lab Worker:**
- Experimenting with reagents, viruses, plants. A role that supports experimenting with different chemicals with testing bays on monkeys for chemical and virology use.

### Equipment

This finally gets around to adding both

Biohazard Equipment for Workers + Closet Spawn - https://github.com/UristMcStation/UristMcStation/pull/826
Spawners for Bioluminescant Orbs: https://github.com/UristMcStation/UristMcStation/pull/824

#### Sprite Credits:

Bimmer123 - (Derelict 12/Stratus Station RIP)

#### Atmospherics/Wiring -

Feel free to shoot improvements wiring + atmospherics wise, I am not atmospherically smart, so some stuff probably sucks.

**Issues Remaining:**

- [x] Add Supervisor's Uniform, Weapon
- [x] Add Lab-Worker + Supervisor Closets.
- [x] Finalize Lower Z-Level
- [x] Balance Pass
- [x] Breakup Map Files
- [x]  Spawners for Biolumescant Orbs
- [ ] Change Self-Destruct System to a Computer, instead of the Nuke, hehe.
- [ ] Finalize Randomized Chemistry Storage System
- [ ] General Styling, Coding Layout
- [ ] Atmospheric Pass

### CODE REVIEW

**Comment by Laniakeaaaa** [comment]
git was screaming

**Comment by Laniakeaaaa** [comment]
Gotta fix a fair bit of stuff, but I'll have some freetime on Monday to give it a shot, hopefully then it'll be mostly ready.

**Comment by Yantarii** [comment]
I'll see if I can fix this up before the merge, now that I've wrapped my head around the weird staircase turf stuff, might come later dependant on work.

**Comment by Yantarii** [comment]
Rebasing to Baymerge in a few days.

**Pull request closed without merging**
