### PR TITLE
Adds Visitor to Assistant Alt-Titles

### PR DESCRIPTION
**Pull request by LorenLuke**

### CODE REVIEW

**Comment by Lyeos** [comment]
I'm not really sure Visitor meshes well with the setting (But will defer to Glloyd's judgement). Passenger might work better, but, eh.

**Review by Naxodile — APPROVED** [review]
Seems fine to me.

**Comment by Naxodile** [comment]
Noticed this is still open, any thoughts on it, Glloyd?

**Comment by Glloyd** [comment]
I think I'll side with Raz here. It'd need to be implemented as a separate role probably to avoid them getting paid. We'll put this to rest for now, but it's an interesting idea.

**Pull request closed without merging**
