### PR TITLE
Motorcycles!

### PR DESCRIPTION
**Pull request by scrdest**
Motorcycles! Proper, oldtimey motorcycles intended for the train event, sprites (well, a sprite, because I only used one) courtesy of Nienhaus and modified to fit 32x32! A child of cargo train tugs, except modified heavier than a regular spriteswap as it turns out the engine on the tugs is an annoying little overlay.

They are:
* Sexy as fuck (pic slightly outdated, the mob sits a bit higher since I decided it looks better, but it's a matter of a couple pixels and could be easily varedited): ;
* Always oriented north, to use the illusion of motion from the moving grass sprite to always appear in motion;
* So is the passenger if in motion; you can turn around while static, but no riding backwards or sideways, shit's dangerous yo;
* Using a tactically placed overlay to create an illusion of a spessman sitting on the actual seat;
* Beefy health-wise (250), since adding them is a bit of a hassle and it's the riders you'll want to shoot at;
* Emagged by default to allow running people over like a proper outlaw biker;
* Intended to be used to create a more Nuke/Invasion-flavored Train round, with soldiers riding to the train and boarding it and crew fighting them off, rather than the Traitor-ish assassins.

Order now and get 100% less redundant PRs and up to 300% more commit-forcing-to-unfuck-branches!

### CODE REVIEW

**Comment by Glloyd** [comment]
Can't automerge, because all three of your PRs affect the same .dmi :disappointed:

**Comment by scrdest** [comment]
Will fix in a second, just gonna commit my YET ANOTHER branch (vamp fixes).

**Comment by scrdest** [comment]
Aaaaaand done.

**Comment by Zuhayr** [comment]
If you're having dmi merge issues look at the dmi tool in the tools folder of the Bay dev repo (probably on master now, too). There's a DMI merge driver that works wonders on .dmi conflicts.

**Comment by Nienhaus** [comment]
Randomly @Zuhayr shows up.

**Comment by Zuhayr** [comment]
I have Urist watched, I keep up to date on the repo. :P

**Comment by Nienhaus** [comment]
Oh, cool.

**Comment by scrdest** [comment]
A wild ZUHAYR appears! ZUHAYR uses HELP! It's super effective!

**Comment by Glloyd** [comment]
Yeah, it should be on master. We'll get it when I finish off this merge in the next couple days.

**Comment by scrdest** [comment]
Well, it's irrelevant to this commit now that I moved them to their own files, now that there's a 4dir one.

**Comment by Glloyd** [comment]
Cannot automerge.

**Comment by scrdest** [comment]
That is odd. Will fix in a sec.

**Comment by scrdest** [comment]
This closed itself... for some reason. And I can't seem to be able to reopen it. Gonna make a new one.

**Pull request closed without merging**
