### PR TITLE
Merge reverts

### PR DESCRIPTION
**Pull request by Naxodile**
Reverts the two sci changes and restores cloning.

### CODE REVIEW

**Comment by Glloyd** [comment]
You should redirect this to @scrdest's merge repo.

**Comment by Naxodile** [comment]
Isn't the merge branch on the main repo now? Scr's branch seems outdated.

**Comment by Glloyd** [comment]
You're right, I forgot Scr made it a main branch.

**Comment by Glloyd** [comment]
It seems mostly fine. Only issue is that .dmi conflicts are generally a bitch to resolve, so we try not to avoid fucking with Bay .dmi's. We could just move the affected icons to urist files and redirect the icons to go there, but I dunno.

**Comment by scrdest** [comment]
You might want to keep me updated regarding any third-party changes to that repo next time. I have a backlog this time, but I've had huge chunks o' update that I just forgot to push, since git was acting up.

Also, I *think* this won't cause issues, but this is still a continuous merge thingummy, so all those .dmi changes in particular might not survive the next pull.

**Comment by Naxodile** [comment]
Changed it to what Glloyd suggested.

**Comment by Glloyd** [comment]
If @scrdest is fine with this, we can go ahead and merge it. I haven't kept up on the merge in the last little bit, so I don't want to mess up his work by merging this.

**Comment by Glloyd** [comment]
This is still in @scrdest's hands

**Comment by Glloyd** [comment]
👍

**Pull request merged**
