### PR TITLE
New song to the Jukebox!

### PR DESCRIPTION
**Pull request by Nienhaus**
List of the songs.
jrtkvn4
See, it was a good idea to get midis!
Anyway, with all the song files together the size is 626.42 KBs which is food for 18 songs. The largest song atm is space.ogg and that's 2,500 KBs. Also for midi quality control you can ask @JacobLee1 if you don't trust my word.

### CODE REVIEW

**Comment by Glloyd** [comment]
I'm not particularly interested in adding copyrighted music to the game. I'm also unsure about increasing the size of the .rsc just to have more songs to play off the jukebox. Yes, it's shit, yes the jukebox is shit, but if we want any change we'd have to port the one from /vg/. PsiOmega from BS12 said he would back in November, so I doubt that's going to happen from their end.

**Comment by Nienhaus** [comment]
So this might as well be closed.

**Comment by Nienhaus** [comment]
There is no point for this to be up. I am now closing this.

**Comment by Glloyd** [comment]
Yeah, sorry. I've been really sick lately.

**Pull request closed without merging**
