### PR TITLE
Updates Urist to Byond 513 - 1536

### PR DESCRIPTION
**Pull request by Glloyd**
Reverts UristMcStation/UristMcStation#916, this is a PR for updating to 513. Hopefully we can figure out the issues we were having and merge this again.

### CODE REVIEW

**Comment by Glloyd** [comment]
@Laniakeaaaa

**Comment by Laniakeaaaa** [comment]
Damn, that's unfortunate. I'll have a look at Bay, see if we missed anything.

**Comment by martinlyra** [comment]
What did break this time?

**Comment by Glloyd** [comment]
@martinlyra The garbage controller. 513 seemed to strain the CPU way more, and it also lagged the garbage controller to hell. So we rolled back for now until we can figure out the issues.

**Comment by martinlyra** [comment]
Weird. I didn't have this issue in the pre-Baymerge fork of Urist that I used for my project. At least what I noticed in my development environment and on the server.

**Comment by Laniakeaaaa** [comment]
Updated it again, maybe god will take pity on us. https://github.com/UristMcStation/UristMcStation/pull/934

**Comment by Glloyd** [comment]
superseded by #996, which I'll need to take a look at.

**Pull request closed without merging**
