### PR TITLE
Energy Sword Improvements and Fixes

### PR DESCRIPTION
**Pull request by Cheedows**
General improvements and additions to energy swords in general as listed below:

- Slightly changed sword activation sound to be closer to a lightsaber and sound cooler in general
- Hitsound has been changed to a classic lightsaber whoosh instead of the generic cutting sound
- Added 3 new esword colours, yellow, orange, and black
- Fix double eswords which have literally been broken for years by the material system Bay implemented, causing it to have no inhand sprites and just be completely busted in general like having it break midfight, or getting the handle embedded into someone else. It's been removed from the material system and just made as a subtype of normal energy swords albeit 2 handed, makes more sense and is less hacky.
- With these fixes are also 2 new colour additions for double eswords as well, in yellow and orange
- New inhands etc. sprites implemented for all of these
- Creating a double esword will take into account the colours when possible, for example a red esword and a blue esword will make a purple double esword. Otherwise if it's a less straightforward colour or the same (for example, purple and red) it will default to the target sword colour.

This should hopefully add some more aesthetics and make them more thematically cool as well fixing long standing bugs that made double eswords unviable for a long time.

### CODE REVIEW

**Comment by Glloyd** [comment]
@Cheedows Your branch must have been outdated, you have icon conflicts. Suffer well brother.

**Comment by Glloyd** [comment]
@Cheedows best way to fix that is to merge with baymerge-testing, and manually resolve the icon conflicts by flagging the files as resolved, and then copying your sprites back into the .dmis. At least that's what I do. Otherwise you're going to lose icons if you just use a git resolve.

**Comment by Cheedows** [comment]
Lol thanks, yeah that sucks I'll have to figure out that conflict.

**Comment by Glloyd** [comment]
@Cheedows any progress on this

**Comment by Naxodile** [comment]
Going to just force-push Cheeds branch and resolve the conflicts

**Comment by Glloyd** [comment]
Thanks @Naxodile

**Comment by Cheedows** [comment]
Thanks @Naxodile, I kinda forgot about and got too busy to fix it up.

**Review by Naxodile — APPROVED** [review]

**Pull request merged**
