### PR TITLE
Holobarrier port from TG.

### PR DESCRIPTION
**Pull request by chaoko99**
🆑 
Adds atmos holobarrier. It blocks atmosphere.
Adds security and engineering holobarriers. Walk through them.
/ 🆑 

NONE of these are mapped yet.

### CODE REVIEW

**Comment by chaoko99** [comment]
Don't know why this is failing.

**Comment by Glloyd** [comment]
Because this more or less negates the point of inflatables, and you haven't mapped any, I think this would be better served as an RnD unlock. That way inflatables still have a point, and this can be viewed as a direct upgrade, and be able to be produced

**Comment by Glloyd** [comment]
Because this more or less negates the point of inflatables, and you haven't mapped any, I think this would be better served as an RnD unlock. That way inflatables still have a point, and this can be viewed as a direct upgrade, and be able to be produced

**Comment by chaoko99** [comment]
I agree! Unfortunately, on that fact alone they will *never* be used because nobody knows how to research, or is actually just that lazy. I was mostly waiting for input on that.
I would *like* to map one in because using inflatables is such a genuinely awful experience the moment you have to pull a dense object like, say, any atmos portable.

**Pull request merged**
