### PR TITLE
adds a little fade effect to lasers and muzzle flashes.

### PR DESCRIPTION
**Pull request by chaoko99**
There really is no purpose to this, anything relating to the results of the effect are purely incidental.

https://streamable.com/6duuc

https://streamable.com/vxr26

### CODE REVIEW

**Comment by chaoko99** [comment]
Might fuck with the easing a bit tomorrow.

**Comment by chaoko99** [comment]
Yeah as is, this can't look any better without new easing types. Go ahead and look it over. No more changes.

**Comment by Glloyd** [comment]
Is the lack of impact effect in the second gif something that's since been fixed? Or an unrelated issue?

**Comment by chaoko99** [comment]
It should be, but I'm gonna check local before saying it is.

**Comment by chaoko99** [comment]
Just tested it. It's good 2 go @Glloyd

**Comment by chaoko99** [comment]
The bug with the pulse rifle is actually due to some ancient shitcode based around the thing originally being deathsquad only.

**Comment by chaoko99** [comment]
pls merj

**Pull request closed without merging**
