### PR TITLE
Bar + Library Z-Level Combination - Baymerge Edition

### PR DESCRIPTION
**Pull request by Yantarii**
Pull Description: Adds a section level of the bar, which is now merged with the Library to give use to both areas.
Moves Command Dorms into the old Library Posistion.

Redone for Baymerge, also tweaked a fair bit of the design, as I didn't like how it looked after not working on it for a while.
No issues w/ Leaky Pipes, Etc in Debug Verbs.

Images: 
jwMqUk9E6R

3hI14Ikfyi

SQDdPaCBEb

DMM View:

image

### CODE REVIEW

**Comment by Yantarii** [comment]
Good to go

**Review by scrdest — APPROVED** [review]
I believe the technical term is 'hella rad'

**Comment by Glloyd** [comment]
whatever map editor you use made a bunch of formatting changes that caused conflicts with #1169. Those will need to be resolved, then I can merge this.

**Comment by Yantarii** [comment]
i think i made it worst lmao, i don't really know how to rebase/fix conflicts that great

**Pull request closed without merging**
