### PR TITLE
Sci outpost changes

### PR DESCRIPTION
**Pull request by Naxodile**
Adds 2 anomalies in containers round start.
Adds 2 extra anomaly containers in the underground.
Adds a regular and radiation med-kit to the first aid wall locker in isolation.
Fixes the anomaly scanner in isolation A only scanning the light bulb.
Fixes the floors under windows not being plating and adds flooring under the doors.
Fixes the emitter in isolation not being setup.

### CODE REVIEW

**Comment by Naxodile** [comment]
Also if someone would tell me how to avoid the 5 merges being included that'd be great.

**Comment by scrdest** [comment]
Don't worry about it. maintainers (read: me and Glloyd) can squash from GitHub, so that won't show up. Or you could do it yourself locally on logs.

**Comment by scrdest** [comment]
All done here? Looks decent to me.

**Comment by Naxodile** [comment]
Can't think of anything else currently, should be ready.

**Comment by Glloyd** [comment]
👍

**Pull request merged**
