### PR TITLE
Shuttles Redux

### PR DESCRIPTION
**Pull request by Vakothu**
Whole bunch of touchups to the shuttles around the map, every shuttle that could reasonably dock with the Nerva can now, and we only need one waypoint per docking port.
Also misc. bug fixes.

### CODE REVIEW

**Comment by Vakothu** [comment]
Gonna close and open the PR to kick Travis, all those checks failed because Github was down.

**Comment by Glloyd** [comment]
Map diff bot isn't working for some reason, so I'm just going to trust that everything's okay mapwise.

**Comment by Vakothu** [comment]
Yeah, it's mostly variable changes to make the docking airlocks actually dock.

**Comment by Glloyd** [comment]
Seems good from my limited testing. Only thing I can see is that the Merc shuttle can't land anymore. Although that might be on me and not on you, I'm not sure.

**Comment by Vakothu** [comment]
Lemme test, I might have buggered something up.

**Comment by Vakothu** [comment]
Okay, I checked and on the server's current version the nuke ops shuttle can't dock either.

**Comment by Vakothu** [comment]
Found the problem, merc docking waypoint has the wrong base_area, and unrelated but the Merc shuttle also doesn't have a docking controller.

**Pull request merged**
