### PR TITLE
Baymerge Staging 03/03/17

### PR DESCRIPTION
**Pull request by scrdest**
Starting from now there hopefully will be more of smaller merges rather than a few fuckhuge cows every couple of months.

### CODE REVIEW

**Comment by Glloyd** [comment]
Have you reverted the shitty stuff you mentioned before?

**Comment by scrdest** [comment]
Not yet, I think the things are actually in this merge commit, but a) it's bundled with other changes, b) I am thinking it through.

Bay removed Nar'Sie cultify effects on objects, that's what I, excuse the pun, object to.

**Comment by Glloyd** [comment]
whats the status on this?

**Comment by scrdest** [comment]
WAAAAAAY too many presentations on Monday. Gonna keep merging Bay/our dev back in small chunks to keep it manageable before cleanup and release when I can spend more time on it.

**Comment by Glloyd** [comment]
https://github.com/Baystation12/Baystation12/pull/16716

fuck Bay with a wire brush. We really should create an issue that holds a list of stuff we need to revert, but this one will have to be selective to avoid dicking with Bay icon files.

**Comment by Glloyd** [comment]
same with this shit if it gets merged: https://github.com/Baystation12/Baystation12/pull/16414

**Comment by Kasuobes** [comment]
> fuck Bay with a wire brush. We really should create an issue that holds a list of stuff we need to revert, but this one will have to be selective to avoid dicking with Bay icon files.

Take it up with @redstryker for being a fucking dickhead.

**Comment by optimumtact** [comment]
or you know, quit building your work on top of someone elses and then whining when they change it to how they desire.

Talk about entitlement.

**Comment by Glloyd** [comment]
Wowee, I'm just addressing stuff that we need to do for our merge, no need to come over here and attack us. I'm just annoyed because Bay used to have a lot of respect for the needs of downstream when it came to icon files. This is just another indication that there is no longer any desire at Bay to help downstream servers. Indeed, that is a large part of why I stopped directly contributing to Bay. Am I annoyed? Yes. But I think of all the places I should be allowed to complain about changes from Bay, it's on the PR (in our own repo) in which we will address these changes, which create more work for us. Even then, I was mostly just joking around with Scrdest. I don't know what compelled you to post here, but it's really just needless hostility.

**Comment by optimumtact** [comment]
I guess I lack the context required to evaulate your comment in the joking tone you indicate you meant it in.

**Comment by Glloyd** [comment]
Yeah, "fuck Bay" is kind of a long running joke in our community. But we made the decision to switch to Bay from /tg/ and stay there, so we obviously don't hate it too much.

**Comment by BlueNexus** [comment]
For the record, I opposed the mentioned PR specifically because it was terrible for downstream.

**Comment by Glloyd** [comment]
I appreciate it Blue, it seems like there's no longer a desire at Bay to consider downstream on things like this anymore.

**Comment by BlueNexus** [comment]
@Glloyd We're working on it.

**Comment by scrdest** [comment]
Continued in #551 due to my incompetence with checking for the correct repo >_>

**Pull request closed without merging**
