### PR TITLE
Security rework

### PR DESCRIPTION
**Pull request by Skeeve2**
Potential complete security rework. View http://www.prevess.com/viewtopic.php?f=4&t=216&sid=1b72b6087265b0e60d603b0a271b9315 for more information on changes. (Latest screenshot below or on last page of forum page.)

Most important changes -

* Removed Permabrig
* Completely changed around where certain areas of security are
* Warden has more control over the prison
* Added Communal Prison
* Added Brig Lobby

Suggested to test this version before committing (if you decide to do so.)

THESE CHANGES HAVE BEEN MADE TO NEWER VERSION VIA SUGGESTIONS FROM FOLLOWING PEOPLE NOT VISIBLE IN SCREENSHOTS OR FORUM POST
* Removed Double-Rwall (Scrdst and Skye)
* Removed shutters exterior & Button (Scrdst)
* Moved secquipment machine to be more accessible (Skye)
* Added more things to do in communal brig such as basketball. (Scrdst)
* Gave warden 1 tile more viewing space (All that was possible. (Skye))

Also fixed various problems involving extra pipes.

### CODE REVIEW

**Comment by Skeeve2** [comment]
After this is pulled or not, I will work on general station fixes such as those from #255

**Comment by Glloyd** [comment]
I'm going to hold a week long poll on this before I decide whether to merge or not.

**Comment by scrdest** [comment]
A double fricking rwall seems a little excessive. If only for consistency - the Vault, supposedly the most secure room, has a single rwall around it (it has two *rooms*, so there are two rwalls to get through, but each of that is a single wall layer).

Also, :-1: until you readd the basketball (maybe add the baskets?), honk.

**Comment by Skeeve2** [comment]
To be fair, the double-rwall is absolutely useless if you REALLY want to orchestrate an escape. The only reason I put a double-rwall / window there was because of the consistent security bombings/hit-and-run window breaking. Since literally 1 window / wall can let every single prisoner out, hit and runs shouldn't be possible. There is still many many weakpoints. 

Also I need to check something and maybe resubmit the pull request maybe so basketballs are probably going in

**Comment by scrdest** [comment]
It won't help. A bombing will take care of the windows either way, and having single rwalls elsewhere means any enterprizing escapee will just pick top-edge walls to deconstruct, since they are less wide and more out of sight. 

Furthermore, for all the 'more interaction', the brig is now cut off from civilians completely, unless Sec agrees to let them in, and with the far more ROUGE SEC we have relative to Bay, it provides for a dangerous buff to Sec's ability to become THE LAW.

**Comment by Skeeve2** [comment]
- If you really want I can resubmit the pull request with the added addition of a basketball/hoop ;)

For the issue of more interaction, there is a visitation booth which is freely accessible, which is the same amount of interaction we have currently. I agree this gives security a bit more power of "GOING NUTS" - but I think it's still a better alternative then the permabrig. I think if we assume good faith security will allow prisoners communal prison and visitation. There shouldn't be any reason to lock a prisoner down unless you are giving them a very short, 5 minute sentence or they are constantly fighting other prisoners, and even then, the lockdowns should be temporary. 

For the "hit and run" issue, the double walls prevent what I have seen in many rounds, which is improvised explosive + cell. It's designed to prevent small explosions, and "breakwindowslol" not dedicated breakouts.

**Comment by Skeeve2** [comment]
See top post

Do not merge this pull request.
A new pull request will be submitted when vote is completed.

THESE CHANGES HAVE BEEN MADE TO NEWER VERSION VIA SUGGESTIONS FROM FOLLOWING PEOPLE NOT VISIBLE IN SCREENSHOTS OR FORUM POST

Removed Double-Rwall (Scrdst and Skye)
Removed shutters exterior & Button (Scrdst)
Moved secquipment machine to be more accessible (Skye)
Added more things to do in communal brig such as basketball. (Scrdst)
Gave warden 1 tile more viewing space (Skye)

**Comment by Skeeve2** [comment]
Updated it, apparently github DOES automatically update it

**Comment by Skeeve2** [comment]
FINAL DEVELOPMENT VERSION. Ready for merging, please start the poll as soon as possible.

**Comment by scrdest** [comment]
Pics plox.

**Comment by Skeeve2** [comment]
Newest iteration : http://i.cubeupload.com/BpRHVU.png

**Comment by Skeeve2** [comment]
Should be ready for poll now @Glloyd

**Comment by Glloyd** [comment]
Perfect. I'll set it up later tonight.

On Thu, Aug 13, 2015 at 1:07 PM, Skeeve2 <notifications@github.com> wrote:

> Should be ready for poll now @Glloyd <https://github.com/Glloyd>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/pull/257#issuecomment-130762922>
> .
>



-- 
Graham Lloyd

**Comment by Skeeve2** [comment]
mistakes

**Comment by Wymar** [comment]
Suggestion: Add some connection between the prison and the courtroom so you can move detainees between the two more easily.

**Comment by Glloyd** [comment]
I'll be switching the armory and the dorms as well as adding maint tunnels that go all the way around and touch on the sec office.

**Comment by Glloyd** [comment]
Once this and the merge are done though.

**Comment by Skeeve2** [comment]
Accidentally merged the wrong update before, fixed and added the courtroom connection while I was at it, easy make.

**Comment by scrdest** [comment]
I'd recommend to hold off until the update goes through. Between the materials system and lighting system rewrites, it'll need some remapping to address the changes or we'll end with darkbrig (since the default tables are darker, and so are the lights - and for souper swanke you can add in red lights during lockdown or whatever).

**Comment by Skeeve2** [comment]
It's being modified along with the rest of the station when the merge is
complete.

**Comment by Skeeve2** [comment]
I somehow managed to keep the holodeck fire removal in this, be warned. I honestly have no idea how that happened.

**Comment by Glloyd** [comment]
Don't worry. I'm not going to be merging this PR, I'm going to be taking
the map and merging Sec in with the post-Baymerge map.

On Wed, Aug 26, 2015 at 12:54 PM, Skeeve2 <notifications@github.com> wrote:

> I somehow managed to keep the holodeck fire removal in this, be warned. I
> honestly have no idea how that happened.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/pull/257#issuecomment-135106729>
> .
>



-- 
Graham Lloyd

**Comment by Glloyd** [comment]
@Skeeve2 the amount of fuckery with the update means this is going to have to be remapped, copying this over is going to be more work than just remapping it at this point. Sorry. When the update gets pushed to master, just update your branch. The vote passed, so we'll get this in at some point, it's just a matter of when.

**Comment by Skeeve2** [comment]
@Gloyyd Didn't you want to make your own changes to it as well?

**Comment by Glloyd** [comment]
This needs to be updated now.

**Comment by Skeeve2** [comment]
I'll start work on the weekend, it should be done fairly quickly, I will also be making some minor changes regarding balance and stuff to do.

**Comment by Glloyd** [comment]
#346

**Pull request closed without merging**
