### PR TITLE
feature: Girlcats

### PR DESCRIPTION
**Pull request by scrdest**
An absurd hellish abomination of a cat with human ears. 
Low dmg, high windup, _fast_. 
Sprites by Ryanwraith w/ my own edits.

,-(_(E.w.)3

girlcat

Based on this classic:
image

EDIT: to clarify, this branch is based off of @ggermanicus 's Baymerge, that's why there's a brazillion commits here right now. Wasn't sure whether to PR straight here or to the Baymerge branch, since it's a new feature.

This code has a hard dependency on the new Bay AI and I CBA to rewrite it back to old AI code temporarily.

### CODE REVIEW

**Comment by Glloyd** [comment]
Retarget this to https://github.com/UristMcStation/UristMcStation/tree/baymerge-testing

**Comment by Glloyd** [comment]
i feel like github is lying about that conflict, but it will need to be resolved

**Comment by scrdest** [comment]
> i feel like github is lying about that conflict, but it will need to be resolved

Might not be, but I needed to fix that DMI anyway vOv

**Comment by Glloyd** [comment]
fixing the dmi seems to have deleted a bunch of sprites from there, check the icon diff.

**Comment by Glloyd** [comment]
might need to just take simpleanimals.dmi out of this pr since the icons were added in #1147 anyways

**Comment by scrdest** [comment]
> might need to just take simpleanimals.dmi out of this pr since the icons were added in #1147 anyways

Good shout, I forgot DMIs are a nightmare - I thought if I just pulled them forward, they'd not diff. Oh blissful ignorance... Guess I should rebase it anyway.

**Pull request merged**
