### PR TITLE
Pipe-layer updates

### PR DESCRIPTION
**Pull request by Andromeda-K22**
🆑 
Pipelayer is now a constructable.
Pipelayer no longer has free metal on spawning.
Circuit design added for constructing the pipelayer.
🆑

### CODE REVIEW

**Comment by Andromeda-K22** [comment]
Always something.

**Comment by Andromeda-K22** [comment]
Sigh. I wish i knew how to squash.

**Comment by scrdest** [comment]
You can do that from the Github web UI now. Otherwise, it's squirreled away in `git rebase`'s flags IIRC.

**Comment by Andromeda-K22** [comment]
Whoever merges this, please squash-merge it.

**Comment by Andromeda-K22** [comment]
Research designs are hell. Who though this was a good idea?

**Pull request closed without merging**
