### PR TITLE
Research remap (for realsies this time)

### PR DESCRIPTION
**Pull request by CPU-Blanc**
Subject to any feedback/objections from the playerbase, it'd be nice to get this merged into testing/master proper.
Full changes & original discussion at #1408 

This will 100% need a rebase/unfuckering with conflicts, but I'll get to that if this gets the go-ahead.

### CODE REVIEW

**Comment by Glloyd** [comment]
This all seems good to me, and it doesn't look like conflicts are actually an issue. We'll see how the tests go, but this might be good to go.

**Comment by CPU-Blanc** [comment]
I don't think it's had any negative feedback, so are we good to assume it passes on that front?

**Comment by Glloyd** [comment]
Yeah, any change to the layout of research has been a long time coming, and this one's been cooking for so long I can't imagine anyone who plays research having an issue with it

**Comment by Glloyd** [comment]
gotta merge this quick so nyx gets more github emails

**Comment by CPU-Blanc** [comment]
My emails are equally getting destroyed. Twice over because of the baymerge into master PR so I get an email for each new commit to baymerge on top of everything else :sob:

**Pull request merged**
