### PR TITLE
[IDB IGNORE] [MDB IGNORE] Merges Baymerge-Testing into Master

### PR DESCRIPTION
**Pull request by Glloyd**
It's been 84 years...

But now the time is almost here.

Only real blocker is #996 and fixing the CI, then testing on the live server running 513.

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Put `[IDB IGNORE]` and `[MDB IGNORE]` in your title please.

You hung the diffbots for **10 minutes** 
image

**Comment by Glloyd** [comment]
Fuck, sorry about that. It's done now.

**Comment by Glloyd** [comment]
With #1078 merged, the only blocker is testing the 514 build on the main server, and if there's no issues, we can finally move back to master.

**Comment by Glloyd** [comment]
Test brought up no critical issues like the kind we had last time. It's finally happening.

**Pull request merged**
